### ISSUE TITLE
App crashing in the RecyclerView Adapter

### ISSUE THREAD

**Issue by Shajeel-Afzal** [Danylo2006/HashTagHelper#5]
Hi Danylo!

I am showing hash tags in the RecyclerView items and `onBindViewHolder` method is simple and looks like this:

```
@Override
    public void onBindViewHolder(TaskViewHolder holder, int position) {

        holder.mTaskTitleTv.setText(mList.get(position).getTitle());

        // pass a TextView or any descendant of it (incliding EditText) here.
        // Hash tags that are in the text will be hightlighed with a color passed to HasTagHelper
        mTextHashTagHelper.handle(holder.mTaskTitleTv);
    }
```

The app crashes when i reach the bottom of the List and scroll up again. 

Complete crash report is:

```
java.lang.IndexOutOfBoundsException: setSpan (0 ... 9) ends beyond length 5
                                                                                     at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1016)
                                                                                     at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:592)
                                                                                     at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:588)
                                                                                     at com.volokh.danylo.hashtaghelper.HashTagHelper.setColorForHashTagToTheEnd(HashTagHelper.java:155)
                                                                                     at com.volokh.danylo.hashtaghelper.HashTagHelper.setColorsToAllHashTags(HashTagHelper.java:115)
                                                                                     at com.volokh.danylo.hashtaghelper.HashTagHelper.eraseAndColorizeAllText(HashTagHelper.java:99)
                                                                                     at com.volokh.danylo.hashtaghelper.HashTagHelper.access$100(HashTagHelper.java:27)
                                                                                     at com.volokh.danylo.hashtaghelper.HashTagHelper$1.onTextChanged(HashTagHelper.java:56)
                                                                                     at android.widget.TextView.sendOnTextChanged(TextView.java:7408)
                                                                                     at android.widget.TextView.setText(TextView.java:3816)
                                                                                     at android.widget.TextView.setText(TextView.java:3671)
                                                                                     at android.widget.TextView.setText(TextView.java:3646)
                                                                                     at com.shajeelafzal.quicktasks_app.adapter.TasksAdapter.onBindViewHolder(TasksAdapter.java:72)
                                                                                     at com.shajeelafzal.quicktasks_app.adapter.TasksAdapter.onBindViewHolder(TasksAdapter.java:25)
                                                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5217)
                                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5250)
                                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4487)
                                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                                     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
                                                                                     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
                                                                                     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3807)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:543)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                     at dalvik.system.NativeStart.main(Native Method)
01-05 01:31:44.324 14479-14550/com.shajeelafzal.quicktasks_app I/Fabric: Crashlytics report upload complete: 568AD6AD00EE-0001-388F-1CE3EAB0099E.cls

```

**Comment by danylovolokh** [comment]
My first guess is that you should create a unique HashTagHelper for every holder in onCreateViewHolder

**Comment by Shajeel-Afzal** [comment]
Yes, That solves the problme. Thanks.

**Comment by CodinggChris** [comment]
I have same issue. How do I "create a unique HashTagHelper for every holder in onCreateViewHolder" ? Please post an example of the unique  HashTagHelper code?
